# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HplJqBvsH1qFqj95cy1HJ4mmyZEGudr3
"""

import sys
import json
import requests
import pandas as pd

df = pd.read_csv('cars.csv')
#df.head()

# Convert CSV to JSON
carsJson = df.to_json(orient='records')
carsJson

# Upload to Firebase
requests.put('https://dsci-551-28ea6-default-rtdb.firebaseio.com/cars.json/', data = carsJson)