# -*- coding: utf-8 -*-
"""search_price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJ5biYnHoO6x48_W3XBH7P-WBQQ6jXyx
"""

#2. 
import sys
import pandas as pd

#price_low=sys.argv[1]
#price_high=sys.argv[2]

price_low=0
price_high=15000


data=requests.get('https://dsci-551-28ea6-default-rtdb.firebaseio.com/cars.json?orderBy="price"&startAt={}&endAt={}'.format(price_low, price_high))

carsDF=pd.read_json(data.text)
carsDF=carsDF.transpose()

#carsDF.head()


priceDF=carsDF[['car_ID', 'price']]

IDs=priceDF['car_ID'].tolist()

if len(IDs)==0:
    print("No cars found within the given range")
else:
    print("IDs for the price range are: ")
    print(IDs)