# -*- coding: utf-8 -*-
"""search_car.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqpGfQOOcvfyze5sKYXIDvIQdJGWk7lZ
"""

#Get data
index_Original = requests.get('https://dsci-551-28ea6-default-rtdb.firebaseio.com/index.json/')
#Convert the jso to a dictionary using json.loads
indexData=json.loads(index_Original.text)
indexData=json.loads(indexData)

from collections import defaultdict
#Now do the reverse of q3

search_string="honda accord"

search_keywords=re.split(r"-| |,|;", search_string)

search_keywords_set = [*set(search_keywords)]

if "" in search_keywords_set:
  search_keywords_set.remove("")

IDs_count=defaultdict(int)

# Go through the keywords in searchkeywordset and mark down in IDs_count each time an ID shows up for that keyword
for keyword in search_keywords_set:
  if keyword in indexData:
    for ID in indexData[keyword]:
      IDs_count[ID]+=1


sorted_IDs={}
sorted_Keys= sorted(IDs_count, key=IDs_count.get, reverse=True)


sorted_Keys

if len(sorted_Keys)==0:
    print("No cars found with given keywords")
else:
    print(sorted_Keys)