# -*- coding: utf-8 -*-
"""Huang_Andrew_HW 1 DSCI 550

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EqljftZL-rMfGC1TH9cRmQBmW0kIPSoc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('flights.csv')
df = df.dropna()

num = df._get_numeric_data()

df.loc[df['arr_delay']<0,'arr_delay']=0
df.loc[df['dep_delay']<0,'dep_delay']=0

#df['dep_delay'].clip(lower=0)
num.head((6))

len(df)

"""Question 1: 1) (25 pts) What is the average departure delay time per month and which month did we have the most departure delays overall?"""

#Avg departure delay time per month

df2 = df.groupby('month')['dep_delay'].mean()
df2.head(12)

#July has the most delays by amount of time (19.57)

"""July has the most delays, 19.57 avg.

2) (25 pts) What is the average arrival and departure delay per air carrier?
"""

# Arrival delays:
arrDelay = df.groupby('carrier')['arr_delay'].mean()
arrDelay.head()

# Departure Delays:
departDelay = df.groupby('carrier')['dep_delay'].mean()
departDelay.head()

"""3) (25 pts) What were the top 5 flights with the worst departure delays?"""

worstDelays=df.sort_values(by='dep_delay', ascending=False)
worstDelays.head(5)

"""(25 pts) How much delay do I need to consider when I use AA in July? (based on
average)
"""

aaJuly=df[(df['month']==7) & (df['carrier']== 'AA')]
#aaJuly.head()

# departure delay
dep_del=aaJuly['dep_delay'].mean()

# answ: 13.934155

# arribal delay
arr_del=aaJuly['arr_delay'].mean()

# answ: 16.693029

dep_del+arr_del

"""Average consider about 13.934 mins departure delay, and 16.693 mins arrival delay, so 31.57 minutes total."""